### ISSUE TITLE
Fails to invoke rustc: error: -g and -C debuginfo both provided

### ISSUE THREAD

**Issue by sdroege** [gnzlbg/cargo-asm#11]
This happens with 1.24 and latest nightly, but only seems to happen inside cargo workspaces. The error happens for every dependency crate it seems.

```
error: -g and -C debuginfo both provided

error: Could not compile `libc`.
```

**Comment by gnzlbg** [comment]
@sdroege I am very sorry for the delay. Do you have a github repository that I could use to reproduce? Also, could you tell me your RUSTFLAGS?

Basically `cargo-asm` passes `-g` to rustc to generate debug-info so that the Rust source code can be mapped to the assembly in some cases. If you are providing `- C debuginfo` simulatenously via RUSTFLAGS or Cargo.toml then it looks that approach doesn't work.

**Comment by gnzlbg** [comment]
@sdroege so I've published a new version with some workarounds. 

First, it does not generate debug info unless you add `--rust` That is, if you don't want to see the Rust code side-by-side then this should now always work.

Second, if you add `--rust` and are also passing `-C debuginfo=X` you can use `--no-debug-info` to disable `cargo-asm` from emitting the `-g` flag. The `-g` flag is basically `-C debuginfo=2` and that is what the library is tested against. If you are using `-C debuginfo=1` thing should still just work. If you  are using `-C debuginfo=0` to disable debugging information, things should also work as long as you don't pass the library the `--rust` flag. If you do pass it that flag, I don't know what will happen. Hopefully either nothing happens, or you will just get an error saying that `cargo-asm` couldn't find line information or something like that.

**Comment by sdroege** [comment]
Maybe it's also related to cdylib. In any case, it still happens. You can reproduce it with e.g. https://github.com/sdroege/gst-plugin-rs/tree/master/gst-plugin-tutorial . I wanted to take a look at the `sinesrc::SineSrc::process` function.

**Comment by sdroege** [comment]
Also thanks for looking and trying to work around it :)

**Comment by gnzlbg** [comment]
So I managed to reproduce it and the fix has been released (0.1.9). Let me know if it fixes it for you as well.

**Comment by sdroege** [comment]
Thanks, that solves it! I can't find any of my functions but that's a different problem

**Comment by sdroege** [comment]
And using it with `--rust` does not work with the same error :)

**Comment by gnzlbg** [comment]
If you are not getting any suggestions for them (e.g. `cargo asm process` might show some) it might well be that they are not part of the generated binary (e.g. because they are removed, or generics but never monomorphized). 

> And using it with --rust does not work with the same error :)

I think the culprit might be this line in the `Cargo.toml` of the project:

https://github.com/sdroege/gst-plugin-rs/blob/ea6f1a5cb803e3764c398f871938b57ffc2ea033/Cargo.toml#L17

It would be cool if you could remove this line and retry and see if the issue persist .

In any case, I've published a new release (0.1.10) that should remove this error :)

**Comment by sdroege** [comment]
Works now, thanks a lot :) Switching off LTO did not make a difference though in the previous version

**Comment by gnzlbg** [comment]
I meant the `debug = true` field :D Anyways, don't worry about that :P
